name: Execute Gradle Task

on:
  workflow_call:
    inputs:
      gradle-task:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Run Gradle Task
        run: ./gradlew ${{ inputs.gradle-task }}
