name: Test egklib-core

on: [push]

jobs:
  core-jvm-test:
    uses: ./.github/workflows/run-gradle-task.yml
    with:
      gradle-task: egklib-core:jvmTest

  core-node-test:
    uses: ./.github/workflows/run-gradle-task.yml
    with:
      gradle-task: egklib-core:jsNodeTest

  core-browser-test:
    uses: ./.github/workflows/run-gradle-task.yml
    with:
      gradle-task: egklib-core:jsBrowserTest
