name: Basic Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: JVM Test
        run: ./gradlew jvmTest
      - name: Node Test
        run: ./gradlew jsNodeTest
