name: Basic Unit Tests

on: [push]

jobs:
  jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: JVM Test
        run: ./gradlew egklib-core:jvmTest

  node:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Java17
          uses: actions/setup-java@v4
          with:
              distribution: 'zulu'
              java-version: '17'
              cache: 'gradle'
        - name: Node Test
          run: ./gradlew egklib-core:jsNodeTest

  browser:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Java17
              uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: '17'
                  cache: 'gradle'
            - name: Browser Test
              run: ./gradlew egklib-core:jsBrowserTest
