name: Basic Unit Tests

on: [push]

jobs:
  jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: JVM Test
        run: ./gradlew jvmTest

  node:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Java17
          uses: actions/setup-java@v4
          with:
              distribution: 'zulu'
              java-version: '17'
              cache: 'gradle'
        - name: Node Test
          run: ./gradlew jsNodeTest
